data = [   {   'arrival_time': '2019-11-02T14:05:00',
        'departure_time': '2019-11-01T07:25:00',
        'duration': 1900,
        'price': 791.57,
        'segments': [   {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 375,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {'Code': 'PDX', 'Name': 'Portland'}},
                        {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 220,
                            'from_place': {'Code': 'PDX', 'Name': 'Portland'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-01T18:16:00',
        'departure_time': '2019-11-01T11:17:00',
        'duration': 479,
        'price': 349.0,
        'segments': [   {   'carrier': {'Code': 'B6', 'Name': 'jetBlue'},
                            'duration': 70,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'BOS',
                                            'Name': 'Boston Logan '
                                                    'International'}},
                        {   'carrier': {'Code': 'B6', 'Name': 'jetBlue'},
                            'duration': 275,
                            'from_place': {   'Code': 'BOS',
                                              'Name': 'Boston Logan '
                                                      'International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-02T11:05:00',
        'departure_time': '2019-11-01T20:14:00',
        'duration': 951,
        'price': 291.0,
        'segments': [   {   'carrier': {'Code': 'B6', 'Name': 'jetBlue'},
                            'duration': 275,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'DEN',
                                            'Name': 'Denver International'}},
                        {   'carrier': {   'Code': 'F9',
                                           'Name': 'Frontier Airlines'},
                            'duration': 118,
                            'from_place': {   'Code': 'DEN',
                                              'Name': 'Denver International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-02T12:35:00',
        'departure_time': '2019-11-01T18:40:00',
        'duration': 1135,
        'price': 445.6,
        'segments': [   {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 385,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'SEA',
                                            'Name': 'Seattle / Tacoma '
                                                    'International'}},
                        {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 240,
                            'from_place': {   'Code': 'SEA',
                                              'Name': 'Seattle / Tacoma '
                                                      'International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-02T05:10:00',
        'departure_time': '2019-11-01T18:40:00',
        'duration': 690,
        'price': 544.98,
        'segments': [   {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 385,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'SEA',
                                            'Name': 'Seattle / Tacoma '
                                                    'International'}},
                        {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 225,
                            'from_place': {   'Code': 'SEA',
                                              'Name': 'Seattle / Tacoma '
                                                      'International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-01T16:37:00',
        'departure_time': '2019-11-01T10:15:00',
        'duration': 442,
        'price': 3231.0,
        'segments': [   {   'carrier': {'Code': '', 'Name': 'Linear Air'},
                            'duration': 45,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'PHL',
                                            'Name': 'Philadelphia '
                                                    'International'}},
                        {   'carrier': {   'Code': 'NK',
                                           'Name': 'Spirit Airlines'},
                            'duration': 227,
                            'from_place': {   'Code': 'PHL',
                                              'Name': 'Philadelphia '
                                                      'International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-01T18:30:00',
        'departure_time': '2019-11-01T07:10:00',
        'duration': 740,
        'price': 457.95,
        'segments': [   {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 380,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'SEA',
                                            'Name': 'Seattle / Tacoma '
                                                    'International'}},
                        {   'carrier': {   'Code': 'AS',
                                           'Name': 'Alaska Airlines'},
                            'duration': 240,
                            'from_place': {   'Code': 'SEA',
                                              'Name': 'Seattle / Tacoma '
                                                      'International'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]},
    {   'arrival_time': '2019-11-02T09:30:00',
        'departure_time': '2019-11-01T13:06:00',
        'duration': 1284,
        'price': 3659.18,
        'segments': [   {   'carrier': {'Code': 'B6', 'Name': 'jetBlue'},
                            'duration': 250,
                            'from_place': {   'Code': 'JFK',
                                              'Name': 'New York John F. '
                                                      'Kennedy'},
                            'to_place': {   'Code': 'IAH',
                                            'Name': 'Houston George Bush '
                                                    'Intercntl.'}},
                        {   'carrier': {'Code': '', 'Name': 'Linear Air'},
                            'duration': 115,
                            'from_place': {   'Code': 'HOU',
                                              'Name': 'Houston Hobby'},
                            'to_place': {   'Code': 'DFW',
                                            'Name': 'Dallas Fort Worth '
                                                    'International'}}]}]
